name: HNPlugin
version: '${project.version}'
author: NiceHello
main: org.hnplugin.hnplugin.HNPlugin
commands:
  hnplugin:
    description: "HN插件主命令"
    permission: hnplugin.command.main
    aliases: hnp
  suicide:
    description: "自杀指令"
    permission: hnplugin.command.suicide
  sudo:
    description: "强制一个玩家执行命令"
    permission: hnplugin.command.sudo
  console:
    description: "以控制台身份执行指令"
    permission: hnplugin.command.console
