name: HNPlugin
version: '1.4.1'
author: NiceHello
main: me.hnplugin.hnplugin.HNPlugin
softdepend: [PlaceholderAPI]
commands:
  hnplugin:
    description: "HN插件主命令"
    permission: hnplugin.command.main
    aliases: hnp
  suicide:
    description: "自杀指令"
    permission: hnplugin.command.suicide
  sudo:
    description: "强制一个玩家执行命令"
    permission: hnplugin.command.sudo
  console:
    description: "以控制台身份执行指令"
    permission: hnplugin.command.console
  tpa:
    description: "请求传送到指定玩家"
    permission: hnplugin.command.tpa
  tpahere:
    description: "请求指定玩家传送到你身边"
    permission: hnplugin.command.tpahere
  tpaccept:
    description: "接受传送请求"
    permission: hnplugin.command.tpaccept
  tpdeny:
    description: "拒绝传送请求"
    permission: hnplugin.command.tpdeny
